# Introducción {-}
[@R-bookdown]  **knitr** [@xie2015].


Sea la **función** de segundo grado $ax^2+bx+c=y$ entonces las raices de esta ecuación se obtiene al despejar la ecuación $ax^2+bx+c=0$ 
\begin{align*}
ax^2+bx+c&=0\\
x^2+\frac{b}{a}x+\frac{c}{a}&=0\\
x^2+2\frac{b}{2a}x+\left(\frac{b}{2a}\right)^2-\left(\frac{b}{2a}\right)^2+\frac{c}{a}&=0\\
\left(x+\frac{b}{2a}\right)^2-\left(\frac{b}{2a}\right)^2+\frac{c}{a}&=0\\
\left(x+\frac{b}{2a}\right)^2&=\frac{b^2}{4a^2}-\frac{c}{a}\\
\left(x+\frac{b}{2a}\right)^2&=\frac{b^2-4ac}{4a^2}\\
\end{align*}
por lo tanto se tiene las raices de la ecuación $ax^2+bx+c=0$ son  $$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

Sean $r_1$ y $r_2$ las raices de la ecuación $x^2+bx+c=0$ entonces la ecuación se puede expresar como $$x^2+bx+c=(x-r_1)(x-r_2)=x^2-(r_1+r_2)x+r_1r_2$$ identificando coeficientes $r_1+r_2=-b$ y $r_1r_2=c$ es decir la suma de las raices es igual al coeficiente de $x$ con el signo cambiado; y el producto de esta es igual al término independiente $c$. 

De otro lado si $r_1$ y $r_2$ las raices de la ecuación $ax^2+bx+c=0$ entonces la ecuación se puede expresar como $$x^2+\frac{b}{a}x+\frac{c}{a}=(x-r_1)(x-r_2)=x^2-(r_1+r_2)x+r_1r_2$$ identificando coeficientes $r_1+r_2=-\frac{b}{a}$ y $r_1r_2=\frac{c}{a}$
